### ISSUE TITLE
mvn install gives nullpointerexception

### ISSUE THREAD

**Issue by tombburnell** [salaboy/emergency-service-drools-app#19]
```
Exception in thread "Thread-0" java.lang.NullPointerException
at com.wordpress.salaboy.TaskServerDaemon.stopServer(TaskServerDaemon.java:72)
at com.wordpress.salaboy.MyDroolsUtilities$1.run(MyDroolsUtilities.java:90)
```

[INFO] ------------------------------------------------------------------------

**Comment by salaboy** [comment]
Hi there.. sounds weird.. I will double check the problem this afternoon.
We are working in UI refactorings.. in a branch, but I will try to fix this problem ASAP.
Thanks for reporting. 

PS: Did you try to run it without tests? to at least have the app working?
Greetings

**Comment by tombburnell** [comment]
ok thanks,

mvn install -Dmaven.test.skip=true 
-> Build successful.

Ok it's built now, how do I start it/ see it in action?

Tom

**Comment by salaboy** [comment]
Hi Tom, first of all thanks for testing the application.
I was fighting with maven, and I've updated the maven conf to be able to run the application using mvn exec:exec. Please do a git pull to get the new source code.
I also improve the README file that explains the basic to run the application. Please feel free to ask questions if something is missing there.
Thanks again!
