### ISSUE TITLE
lwjgl-native not found

### ISSUE THREAD

**Issue by CedricLevasseur** [salaboy/emergency-service-drools-app#27]
Hi, 
When i run 
mvn -Pword-ui in the run directory of the master branch,
i get this error : 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:
2.1:unpack (default-cli) on project emergency-service-run: Unable to find artifa
ct. Failure to find org.lwjgl:lwjgl-native:jar:win:2.6 in http://b2s-repo.google
code.com/svn/trunk/mvn-repo/ was cached in the local repository, resolution will
 not be reattempted until the update interval of b2s-repo has elapsed or updates
 are forced

HELP !

**Comment by CedricLevasseur** [comment]
lwjgl-native is present on the website, which is not down. I don't understand why i can't download it.
Ant the manuel download doesn't seems to work  
$ mvn install:install-file -DgroupId=org.lwjgl -DartifactId=lwjgl-native -Dvers
ion=2.6 -Dclassifier=win32 -Dpackaging=jar -Dfile=/tmp/lwjgl-native-2.6-win32.j
ar

**Comment by salaboy** [comment]
It's a good question, I didn't have the chance to test it on windows. We know that it works well for Mac OSX and Linux (32 & 64bits) but in windows it should work.. 
This page shows the repo: http://code.google.com/p/b2s-repo/source/browse/trunk/mvn-repo/org/lwjgl/lwjgl-native/2.6/
and it contains the win32 and win64 native libs.. probably we need to change the profile and add the 32 and 64 tags to that dependencies. Can you test that changing the win profile inside the run/pom.xml file?
Cheers

**Comment by CedricLevasseur** [comment]
$ git diff pom.xml
diff --git a/run/pom.xml b/run/pom.xml
old mode 100644
new mode 100755
index 3fdef09..a84aabc
--- a/run/pom.xml
+++ b/run/pom.xml
@@ -63,7 +63,7 @@
                 </os>
             </activation>
             <properties>
-                <platform>win</platform>
-                <platform>win32</platform>
           </properties>
       </profile>
       <profile>

You're right, it works for me ! Thanks !!

**Comment by CedricLevasseur** [comment]
Grr,  markdown syntax drop my patch.

i've just replace `win` with `win32` in the platform tag of the run/pom.xml file and it works !

**Comment by dmoralesgpm** [comment]
Solved:

```
   <profile>
        <id>win32</id>
        <activation>
            <os>
                <family>windows</family>
            </os>
        </activation>
        <properties>
            <platform>win32</platform>
        </properties>
    </profile>
```

Change line 66 to win32

**Comment by dmoralesgpm** [comment]
sorry, i haven't read your previous comments.

**Comment by salaboy** [comment]
Done
