### ISSUE TITLE
Heart Attack Issues (one)

### ISSUE THREAD

**Issue by dmoralesgpm** [salaboy/emergency-service-drools-app#28]
Hi there,

We are trying to complete the heart attack use case but it appears to be some issues here. (ruleML branch, first of all)

We are running:

1) core, 2) world-ui, 3) tasks-list (swing) 4) dashboard-ui.

And this is the first test (result, no patient at hospital)

1) Hit space in world ui
2) Complete the operator task: heart attack, 1 person.
3) Complete the control task: DefaultHeartAttackProcedure
4) Complete the garage task: strokes vehicle
5) Drive car to the emergency 
6) Complete doctor task: Severity 1
7) Drive to the selected hospital

And when the vehicle reachs the hospital...

1) The core shows a report in console. No errors
2) The hospital in the world-UI stops lighting
3) There is no tasks in the taskslist-ui
4) In the dashboard. We see the message (hospital reached) in the live report. But we don't see the hospital status.

In the dashboard console there are some errors:

Exception in thread "Thread-6" java.lang.NullPointerException
        at com.wordpress.salaboy.messaging.MessageConsumer.receiveMessage(MessageConsumer.java:61)
        at com.wordpress.salaboy.messaging.MessageConsumerWorker.run(MessageConsumerWorker.java:39)

And so on (different  threads). 

The same result If you try with taskslist-ui-web instead of the swing app.

**Comment by esteban-aliverti** [comment]
The Hospital tab of Dashboard was never coded :) So, do not expect to see a list of patients there. 
This could be a nice feature to contribute with ;)

**Comment by dmoralesgpm** [comment]
Ok, so... when the vehicle reachs the hospital, the use case is ended. Is it true?

**Comment by dmoralesgpm** [comment]
and... i've seen advanced features in this video (http://www.vimeo.com/18343529). Like selecting medical kit and doctor when you select the vehicle or another role to view reports...

Do you plan to update master branch with this kind of features?

Thanks.

**Comment by salaboy** [comment]
fixed in master
