### ISSUE TITLE
Heart Attack Issues (two)

### ISSUE THREAD

**Issue by dmoralesgpm** [salaboy/emergency-service-drools-app#29]
Hi there again,

We are trying to complete the heart attack use case but it appears to be some issues here. (ruleML branch, first of all)

We are running:

1) core, 2) world-ui, 3) tasks-list (swing) 4) dashboard-ui.

And this is the second test (result, no vital signs graph)

1) Hit space in world ui
2) Complete the operator task: heart attack, 1 person.
3) Complete the control task: DefaultHeartAttackProcedure
4) Complete the garage task: strokes vehicle
5) Drive car to the emergency
6) Complete doctor task: Severity 1
7) Press q and w keys in the world ui.

Well, we can see the HeartBeat Messages in the live report, and also we can see the alerts (heart attack if you press fast and no signal if you stop).

But, we don't see any graph at dashboard-ui.

There is no errors in consoles (none of them).

**Comment by dmoralesgpm** [comment]
Hi there, 

If you look at this picture you could see that the Tab is outside the panel (jTabbedPane)

http://img215.imageshack.us/img215/595/dashboarde.jpg

so it's impossible to see it or interact with it.

I'm searching in the source code so maybe i will find the bug, but i think that you probably will do that faster :)

Thanks

**Comment by salaboy** [comment]
Thanks for the feedback, we know about that, is a vertical tab that we can probably remove. We are creating dynamic tabs in dynamic frames and we are not swing experts :). We will remove that tab in future releases, right now it doesn't look good but it doesn't break anything
