### ISSUE TITLE
Error in Control Form

### ISSUE THREAD

**Issue by dmoralesgpm** [salaboy/emergency-service-drools-app#32]
Testing Heart Attack in master branch:

When i try to access the control form, in web-ui, it returns an error.

HTTP ERROR 500

Problem accessing /emergency-services/task/co/control/Default/cf2fe2db-60e0-488d-ac74-833280cef9b8-@-2/SuggestedProcess-%3E0. Reason:

```
[Error: unresolvable property or identifier: patient]
```

[Near : {... patient.age ....}]
             ^
[Line: 1, Column: 1]

**Comment by CedricLevasseur** [comment]
I've exactly the same error !

**Comment by CedricLevasseur** [comment]
Hi to the "Emergency" team 
Could you confirm the problem ?
Do you have a way to solve it ?
thanks

**Comment by dmoralesgpm** [comment]
This error is not present in ruleML branch. If you want to have a working version, you should try with this branch.

I've tested the heart attack use case, and it's working 90% perfect. You can not view the live report of vital signs (https://github.com/Salaboy/emergency-service-drools-app/issues/29) but at least you can test the full use case.

**Comment by salaboy** [comment]
We have just merge V3 in master and is fixed
