### ISSUE TITLE
snakeyaml version in RuleML branch

### ISSUE THREAD

**Issue by CedricLevasseur** [salaboy/emergency-service-drools-app#33]
Please correct the snakeyaml version in the ruleML branch :
1.9
instead of  1.9-SNAPSHOT

thks

**Comment by salaboy** [comment]
Thanks for reporting this.. did you test this change?
So I can go ahead and doing it? if you do, please send a pull request or let me know and I will directly push the changes

**Comment by CedricLevasseur** [comment]
yes i've testing the change ! it's ok.
you can push the modif. 
Thanks.

**Comment by salaboy** [comment]
done
